# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Terraform Validate
description: Runs a test on the terraform

inputs:
  target:
    description: Target directory
    required: true

runs:
  using: composite
  steps:
    - name: Tofu Format
      uses: ./.github/actions/tofu-format
      with:
        target: ${{ inputs.target }}

    - name: Tofu Scanning
      uses: ./.github/actions/tofu-scan
      with:
        target: ${{ inputs.target }}
