#cloud-config
hostname: ${hostname}.local
prefer_fqdn_over_hostname: false
users:
  - name: ${node_user}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
    %{ for key in authorized_keys ~}
    - ${key}
    %{ endfor ~}
ssh_pwauth: False
runcmd:
  - |
    # If no cluster connect hostname/ip is provided then start RKE2 as single node/bootstrap
    if [ -z ${connect_hostname} ]; then
      server_ip=$(ip route get $(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+') | grep -oP 'src \K\S+')
    else
      server_ip=${connect_hostname}
      # If server node(s) are ready then an unauthenticated request to the kube api should return a 401
      until [[ $(curl -m 5 --silent -I https://$${server_ip}:6443 -k | head -n 1|cut -d$' ' -f2) == 401 ]]; do
        echo "Waiting for cluster to be available."
        sleep 5
      done
    fi
    if [ "${taint_servers}" == "true" ]; then
      tee -a /etc/rancher/rke2/config.yaml <<EOF >/dev/null
    node-taint:
      - node-role.kubernetes.io/control-plane=:NoSchedule
    EOF
    fi
    # If an NTP server address is passed in then overwrite chrony.conf with settings needed for using custom NTP server
    if [ "${ntp_server}" ]; then
      # copy default chrony.conf into a new file as a reference
      cp /etc/chrony.conf /etc/chrony.defaultconf
      # Grab server IP and use it to find the subnet that the server is on
      host_ip=$(ip route get $(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+') | grep -oP 'src \K\S+')
      subnet=$(ip route | grep "src $${host_ip}" | awk '{print $1}')
      # Overwrite default chrony.conf with custom NTP server information
      tee /etc/chrony.conf <<EOF >/dev/null
    # Server/IP to use for NTP
    server ${ntp_server} iburst
    # Record the rate at which the system clock gains/losses time.
    driftfile /var/lib/chrony/drift
    # Specify directory for log files.
    logdir /var/log/chrony
    log measurements statistics tracking
    # Allow the system clock to be stepped in the first three updates
    # if its offset is larger than 1 second.
    makestep 1.0 3
    # Specify file containing keys for NTP authentication.
    keyfile /etc/chrony.keys
    commandkey 24
    # Serve time even if not synchronized to a time source.
    local stratum 10
    initstepslew 20 ntp1.example.net
    # Enable kernel synchronization of the real-time clock (RTC).
    rtcsync
    # Allow NTP client access from local network.
    allow $${subnet}
    # Get TAI-UTC offset and leap seconds from the system tz database.
    leapsectz right/UTC
    EOF
    fi
    /root/rke2-startup.sh -t ${token} -s $${server_ip} ${agent} ${tls_san}
