#cloud-config
hostname: ${hostname}.local
prefer_fqdn_over_hostname: false
users:
  - name: ${node_user}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
    %{ for key in authorized_keys ~}
    - ${key}
    %{ endfor ~}
ssh_pwauth: False
runcmd:
  - |
    # If no cluster connect hostname/ip is provided then start RKE2 as single node/bootstrap
    if [ -z ${connect_hostname} ]; then
      server_ip=$(ip route get $(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+') | grep -oP 'src \K\S+')
    else
      server_ip=${connect_hostname}
      # If server node(s) are ready then an unauthenticated request to the kube api should return a 401
      until [[ $(curl -m 5 --silent -I https://$${server_ip}:6443 -k | head -n 1|cut -d$' ' -f2) == 401 ]]; do
        echo "Waiting for cluster to be available."
        sleep 5
      done
    fi
    /root/rke2-startup.sh -t ${token} -s $${server_ip} ${agent} ${tls_san}
