# This reusable workflow plans a given environment (IAC + Validate Bundle availability)
name: Validate
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write
  packages: read

jobs:
  terraform_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/actions/terraform-test
        with:
          target: modules
